### ISSUE TITLE
Ngl no idea what this is

### ISSUE THREAD

**Issue by Omena0** [face-hh/griddycode#115]
**Describe the bug**
File picker bugged

**To Reproduce**
1. Open GriddyCode
2. Open file picker

**Expected behavior**
File picker opens.

**Screenshots**
![image](https://github.com/face-hh/griddycode/assets/82773737/44a696e6-5ff9-4ab0-a142-668eb0b7d4ca)
![image](https://github.com/face-hh/griddycode/assets/82773737/355fe91c-9729-4baa-b754-dfe147ad36a9)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.2.1

**Comment by face-hh** [comment]
`DirAccess.open(path)` has failed, the `path` is probably invalid. I believe the only way to debug it is to install Godot, navigate to
https://github.com/face-hh/griddycode/blob/e064631577ac4226f9567c4610bf50c89b80f3c6/Scripts/file_dialog.gd#L36
and add a line above:
```
print(editor.current_dir)
```

**Comment by Omena0** [comment]
Ok Ill try that, i recently updated my graphics drivers (restart didint fix) so it might somehow relate to that because before it worked perfectly fine.

**Comment by Omena0** [comment]
Ok, well after running godot, it randomly started working again... No idea how that would change anything but it works now LMAO

**Comment by face-hh** [comment]
I might have an idea - when you run the project through Godot, due to it running in debug it gets the debug file path as the first CLI argument - path that is most certainly valid, unlike the one it initially assumed when being ran from the command line.

I'll still leave the issue closed as I haven't received any reports of this happening to others. Thanks for reporting it! :slightly_smiling_face:
